name: |
  Brand new

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  pr-check: 
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache file
        uses: actions/cache@v2
        with:
          path: hello2.txt
          key: v1-hello-${{ hashFiles('hello2.txt') }}
          restore-keys: |
            v1-hello-${{ hashFiles('hello2.txt') }}
            v1-hello

      - name: echo
        run: echo 'xasxasxaxs' > hello2.txt
