name: PR check

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  pr-check: 
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache file
        uses: actions/cache@v2
        with:
          path: hello2.txt
          key: v2-hello-${{ hashFiles('hello2.txt') }}
          restore-keys: |
            v2-hello-${{ hashFiles('hello2.txt') }}
            v2-hello

      - name: create file
        run: echo 'helloxxx' > hello2.txt

