name: PR check

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  pr-check: 
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache file
        uses: actions/cache@v2
        with:
          path: test.txt
          key: v1-test-${{ hashFiles('test.txt') }}
          restore-keys: |
            v1-test-${{ hashFiles('test.txt') }}
            v1-test

      - name: cat
        run: cat test.txt

